### ISSUE TITLE
rendering notebook

### ISSUE THREAD

**Issue by rheiland** [marcjwilliams1/neutral-tumour-evolution-williams-2018#1]
In your README, you say "notebook should render in github after clicking on it", but that is not true for me.

**Comment by marcjwilliams1** [comment]
Sorry, don't know why it's not working, it's always worked in the past. You can take a look here though: https://nbviewer.jupyter.org/github/marcjwilliams1/neutral-tumour-evolution-williams-2018/blob/master/Generate%20Figures.ipynb
